config/routes.rb
Honeybadger::Application.routes.draw do
  get "feedbacks/new"
  get "feedbacks/create"
  get "search_results_controller/search"
  root 'pages#home'
  get "/home2" => "pages#home2"
 

  devise_scope :user do
	post "/users" => "users/registrations#append_or_create" , as: "user_registration"
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }

  devise_for :admins, controllers: { sessions: "admins/sessions" }

  get "home_programs_json" => 'programs#json_list'
  get "selectprogram" => "programs#select_program"

  
  get "pages/channel"
  get "/about" => "pages#about"
  get '/search/find_courses_from_program_and_semester' => 'search_results#find_courses_from_program_and_semester'
  get '/search/find_programs_from_university_and_branch' => 'search_results#find_programs_from_university_and_branch'
  get '/search/get_course' => 'search_results#get_course'
  get '/university_courses/:id/new_qpaper' => 'university_courses#new_qpaper' , as: "university_courses_new_qpaper"
  get '/courses/:id/new_question' => 'courses#new_question' , as: "course_new_question"
  
  post '/questions/:question_id/addanswer' => 'questions#submit_answer'
  post 'solutions/accept' => 'solutions#accept'
  get '/yourquestions' =>'questions#yourquestions'
  get '/youranswers' => 'solutions#yoursolutions'
  get '/schedule/:program/:semester' => 'programs#schedule'

  resources :qpapers
  resources :questions
  resources :courses
  resources :examquestions
  resources :branches
  resources :universities
  resources :programs
  resources :institutions
  resources :university_courses
  resources :solutions
  resources :wikis
  resources :notes
  resources :units
  resources :program_university_courses
  resources :qpaper_files
  resources :text_book_sale_offers, only: [:create, :update, :destroy]
  resources :feedbacks, only: [:new, :create]

  

end

app/controllers/university_courses_controller.rb
class UniversityCoursesController < ApplicationController
  before_action :set_university_course, only: [:show, :edit, :update, :destroy, :new_qpaper]
  before_filter :authenticate_admin!, except: [:index, :show]
  # GET /university_courses
  # GET /university_courses.json
  def index
    @university_courses = UniversityCourse.all
  end

  # GET /university_courses/1
  # GET /university_courses/1.json
  def show
  end

  # GET /university_courses/new
  def new
    @university_course = UniversityCourse.new
  end

  def new_qpaper
	@qpaper = @university_course.qpapers.build
	@qpaper.examquestions.build.build_question
	render "qpapers/new"
  end

  def create_qpaper
    @qpaper = Qpaper.new(qpaper_params)  
    @qpaper.user_id = current_user.id
    @qpaper.examquestions.each do |eq|
	 eq.user_id = current_user.id
	 eq.question.user_id ||= current_user.id
	 eq.question.course_id ||= UniversityCourse.find(@qpaper.university_course_id).course_id
    end
    respond_to do |format|
      if @qpaper.save!
        format.html { redirect_to @qpaper, notice: 'Question paper was successfully created.' }
        format.json { render action: 'qpapers/show', status: :created, location: @qpaper }
      else
        format.html { render action: 'qpapers/new' }
        format.json { render json: @qpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /university_courses/1/edit
  def edit
  end

  # POST /university_courses
  # POST /university_courses.json
  def create
    @university_course = UniversityCourse.new(university_course_params)

    respond_to do |format|
      if @university_course.save
        format.html { redirect_to @university_course, notice: 'University course was successfully created.' }
        format.json { render action: 'show', status: :created, location: @university_course }
      else
        format.html { render action: 'new' }
        format.json { render json: @university_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /university_courses/1
  # PATCH/PUT /university_courses/1.json
  def update
    respond_to do |format|
      if @university_course.update(university_course_params)
        format.html { redirect_to @university_course, notice: 'University course was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @university_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /university_courses/1
  # DELETE /university_courses/1.json
  def destroy
    @university_course.destroy
    respond_to do |format|
      format.html { redirect_to university_courses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university_course
      @university_course = UniversityCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def university_course_params
      params.require(:university_course).permit(:university_id, :course_id, :course_code)
    end

    def qpaper_params
      params.require(:qpaper).permit(:year, :title, :exam_name,  :official, :university_course_id, :program_ids, :month, :semester,  examquestions_attributes: [:mark, :qnumber, :id, :question_id,:subquestion_no,  {question_attributes: [:qtext, :qdesc, :id]}])
    end

end

app/helpers/university_courses_helper.rb
module UniversityCoursesHelper
end

app/views/university_courses/_form.html.erb
<%= simple_form_for @university_course, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.association :university %>
  <%= f.association :course %>
  <%= f.input :course_code %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                university_courses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/university_courses/_wmd_script.html.erb
<script type="text/javascript">
    $(function () {

        new Markdown.Editor(Markdown.getSanitizingConverter()).run();
        
    });
</script>

app/views/university_courses/edit.html.erb
<%- model_class = UniversityCourse -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/university_courses/index.html.erb
<%- model_class = UniversityCourse -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>University</th>
      <th>Course</th>
      <th>Course Code</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @university_courses.each do |university_course| %>
      <tr>
        <td><%= link_to university_course.id, university_course_path(university_course) %></td>
        <td><%= university_course.university.name %></td>
        <td><%= university_course.course.name %></td>
        <td><%= university_course.course_code %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_university_course_path(university_course), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      university_course_path(university_course),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_university_course_path,
            :class => 'btn btn-primary' %>

app/views/university_courses/new.html.erb
<%- model_class = UniversityCourse -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/university_courses/new_qpaper.html.erb
<div class="page-header">
  <h2>New question paper</h2>
</div>

<%= simple_nested_form_for @qpaper, :html => { :class => 'form-horizontal' } do |f| %>
<div class="well">
  <%= f.input :year , collection: 2013.downto(1990) %>
  <%= f.input :title %>
  <%= f.input :exam_name %>
  <%= f.input :university_course_id, :as => :hidden, :input_html => { :value => @university_course.id } %>
  <%= f.association :programs , label_method: :short_desc, as: :check_boxes %>
  <%= f.input :month %>
  <%= f.input :semester %>
  <%= f.input :official %>
</div>
  <%= f.simple_fields_for :examquestions do |examquestion_form| %>
    <div class="well">
	    <%= examquestion_form.input :qnumber, label: "Question Number:"  %>
	    <%= examquestion_form.input :mark, label: "Mark:"  %>
	    <%= examquestion_form.input :subquestion_no, label: "Sub-question number:"  %>
		   <%= examquestion_form.association :question ,collection: @university_course.course.questions.order("qtext ASC"), label_method: :qtext %>
			<div class="row"><div class="span1 offset3">OR</div></div>
		   <%= examquestion_form.simple_fields_for :question do |question_form| %>
		    <%= question_form.input :qtext, label: "Question:"  %>
		    <%= question_form.input :qdesc, label: "Question Details:"  %>
		  <% end %>   
    </div> 
  <% end %>
  <p><%= f.link_to_add( :examquestions, model_object: Examquestion.new.tap{ |eq| eq.build_question }, class: "btn btn-primary" ) do%>
   Add Question
   <% end %></p>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                qpapers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/university_courses/show.html.erb
<% content_for :title do %>
<%= "Karpeer - "+@university_course.full_course_name %>
<% end %>

<% content_for :mathjax_scripts do %>
<%= render partial: 'partials/mathjax_include' %>
<% end %>
<% content_for :prettify_scripts do %>
<%= render partial: 'partials/prettify_include' %>
<% end %>
<% content_for :pagewise_heading do %>
	<%= @university_course.course_code+" - "+@university_course.course.name %>
<% end %>
<% content_for :navbar_breadcrumbs do %>
<ul class="nav">
	  <li><%= link_to root_path  do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><%end %></li>
<li><%= link_to '#' do %><%= @university_course.full_course_name %> &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
	</ul>
<% end %>

<div class="right-bordered-box">
  <div class="heading"><h4>Question Papers</h4></div>
	<div class="bordered-box-content">
	  <% cache @university_course do%>
			<% qpapers = @university_course.qpapers %>
			<% if qpapers.length > 0 then %>
			<ol>
			<% qpapers.each do |qp| %>
			<li>
			<div class="customLink"><%= link_to qp.title+" "+qp.month+" "+qp.year.to_s, qpaper_path(qp.id)+"?uc="+@university_course.id.to_s %></div>
			
			</li>
			<% end %>
			</ol>
			<% else %>
			There are no question papers yet for this course.
			<% end %>
			<div id="underlined-h5"><h5>Upload a question paper</h5></div>
			<%= bootstrap_flash %>
			<%= simple_form_for :qpaper_file, :url => qpaper_files_path, :html => { :multipart => true } do |form| %>
			  <%= form.file_field :uploaded_file %>
			  <%= form.input :university_course_id, :as => :hidden, :input_html => { :value => @university_course.id } %>
			  <%= submit_tag "Upload", class: "btn btn-success" %>
			<% end %>
		<% end %>
	    </div><!-- bordered-box-content -->
</div><!-- bordered-box -->





<div class="right-bordered-box">
  <div class="heading"><h4>Questions</h4></div>
	  <div class="bordered-box-content">
	    <% cache (@university_course.course) do%>
		<p><h5> <%= link_to "Add a question" , new_question_path+"?course="+@university_course.course_id.to_s, class: "btn btn-success" %> </h5></p>
			<% if Question.where(course_id: @university_course.course_id).where(standalone: true).count > 0 then %>
				<h5>Questions added by Users</h5>
				<ol>
				<% Question.where(course_id: @university_course.course_id).where(standalone: true).each do |q| %>
        <% cache (q) do %>
				<li><div class="customLink"><%= link_to (q.qtitle || q.qtext), question_path(q.id)+"?uc="+@university_course.id.to_s %></div></li>
        <% end %>
				<% end %>
				</ol>
			<% end %>
			<% if Question.where(course_id: @university_course.course_id).where(standalone: false).count > 0 then %>
				<h5>Questions obtained from question papers</h5>
				<% questions = Question.includes(:examquestions).where(course_id: @university_course.course_id).where(standalone: false).order('examquestions.mark ASC').group_by { |q| q.examquestions.first.mark } %>
				<% questions.keys.each do |mark| %>
				<h6><%= mark %> Marks</h6>
				<ol>
				<% questions[mark].each do |q| %>
        <% cache (q) do %>
				 <li><div class="customLink"><%= link_to (q.qtitle || q.qtext), question_path(q.id)+"?uc="+@university_course.id.to_s %></div></li>
        <% end %>
				<% end %>
				</ol>
				<% end %>
			<% end %>
<%# render partial: "partials/questions", locals: { questions: @program_university_course.university_course.course.questions } %>
	<% end %>
	    </div>
</div>