config/routes.rb
Honeybadger::Application.routes.draw do
  get "feedbacks/new"
  get "feedbacks/create"
  get "search_results_controller/search"
  root 'pages#home'
  get "/home2" => "pages#home2"
 

  devise_scope :user do
	post "/users" => "users/registrations#append_or_create" , as: "user_registration"
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }

  devise_for :admins, controllers: { sessions: "admins/sessions" }

  get "home_programs_json" => 'programs#json_list'
  get "selectprogram" => "programs#select_program"

  
  get "pages/channel"
  get "/about" => "pages#about"
  get '/search/find_courses_from_program_and_semester' => 'search_results#find_courses_from_program_and_semester'
  get '/search/find_programs_from_university_and_branch' => 'search_results#find_programs_from_university_and_branch'
  get '/search/get_course' => 'search_results#get_course'
  get '/university_courses/:id/new_qpaper' => 'university_courses#new_qpaper' , as: "university_courses_new_qpaper"
  get '/courses/:id/new_question' => 'courses#new_question' , as: "course_new_question"
  
  post '/questions/:question_id/addanswer' => 'questions#submit_answer'
  post 'solutions/accept' => 'solutions#accept'
  get '/yourquestions' =>'questions#yourquestions'
  get '/youranswers' => 'solutions#yoursolutions'
  get '/schedule/:program/:semester' => 'programs#schedule'

  resources :qpapers
  resources :questions
  resources :courses
  resources :examquestions
  resources :branches
  resources :universities
  resources :programs
  resources :institutions
  resources :university_courses
  resources :solutions
  resources :wikis
  resources :notes
  resources :units
  resources :program_university_courses
  resources :qpaper_files
  resources :text_book_sale_offers, only: [:create, :update, :destroy]
  resources :feedbacks, only: [:new, :create]

  

end

app/models/program.rb
class Program < ActiveRecord::Base
	has_many :program_university_courses
	has_many :university_courses, through: :program_university_courses
	has_many :users
	belongs_to :university, touch: true
	belongs_to :branch
	has_and_belongs_to_many :qpapers

	validates_uniqueness_of :degree_name, scope: [:university_id, :branch_id]
	accepts_nested_attributes_for :program_university_courses,  reject_if: proc { |attributes| attributes['semester'].blank?  }
 
	def degree_short
		case self.degree_name
			when 'Bachelor of Engineering'
				return 'B.E'
			when 'Bachelor of Technology'
				return 'B.Tech'
			else
				return nil
		end
	end

	def short_desc
		degree_short + " - " + self.branch.abbreviation + " - " + self.university.name
	end

	def shorter_desc
		degree_short + " - " + self.branch.name
	end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [ :edit, :update, :destroy]
  before_filter :authenticate_admin!, except: [:index, :show, :json_list, :schedule, :select_program]
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
	eager_load_program
  end

  def schedule
    @program=Program.find(params[:program])
    @exams=Exam.where( university_course_id: ProgramUniversityCourse.select(:university_course_id).where(program_id: @program.id,semester: params[:semester] )).order(:date)
  end

  def json_list
	render json: University.select([:id, :name]).includes(:branches, :programs => [:program_university_courses => { :university_course => :course }]).load.map{|u| {"label" => u.name, "children" => u.programs.to_a.map{ |p| {"label" => p.shorter_desc , "children" => (1..8).map{|x| { "label" => "Semester "+x.to_s, "children" => p.program_university_courses.select{ |puc| puc.semester==x && puc.university_course !=nil }.map{ |puc1| { "label"=> puc1.university_course.full_course_name } }  }} }} }}.to_json
  end

  # GET /programs/new
  def new
    @program = Program.new
    @program.program_university_courses.build.build_university_course.tap{|uc| 5.times { uc.units.build } }.build_course
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)
    @program.program_university_courses.each { |puc| puc.university_course.university_id = @program.university_id }
    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, notice: 'Program was successfully created.' }
        format.json { render action: 'show', status: :created, location: @program }
      else
        format.html { render action: 'new' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end

  def select_program
    @program=Program.find(params[:program_choice])
    render partial: "program_details", locals: {p: @program}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    def eager_load_program
      @program = Program.includes(program_university_courses: {university_course: :course }).find(params[:id])
    end
    def schedule_params
      params.permit(:semester, :program)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:degree_name, :branch_id, :university_id, program_university_courses_attributes: [:semester, :elective, :credits , :university_course_id, :id,  { university_course_attributes: [:id, :course_code, :university_id, :course_id , { course_attributes: [:id, :name, :practical, :branch_id]}, units_attributes: [:id, :unit_number, :name,  :unit_curriculum ] ] }])
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= simple_nested_form_for @program, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="well">
  <%= f.input :degree_name %>
  <%= f.association :university %>
  <%= f.association :branch %>
  </div>
  <%= f.simple_fields_for :program_university_courses do |program_university_course_form| %>
    <div class="well linenBg">
	  <%= program_university_course_form.input :semester %>
	  <%= program_university_course_form.input :elective %>
	  <%= program_university_course_form.input :credits %>
	  <% if action == "edit" then %>
	  <%= program_university_course_form.input :id, :as => :hidden, :input_html => { :value => program_university_course_form.object.id } %>
	  <% end %>
	<div class="well honeyDewBg">
	<div class="row"><div class="span9">Select an existing university course</div></div>
	  <%= program_university_course_form.input :university_course_id, collection: UniversityCourse.all , label_method: :full_course_name , value_method: :id %>
			</div><div class="well honeyDewBg">
			<div class="row"><div class="span9">OR create a new university course</div></div>
		   <%= program_university_course_form.simple_fields_for :university_course do |university_course_form| %>
			  <%= university_course_form.input :course_code %>
			  <% if action == "edit" then %>
			 <%= university_course_form.object.id %>
			  <%= university_course_form.input :id, :as => :hidden, :input_html => { :value => university_course_form.object.id } %>
			  <% end %>
			<div class="well bisqueBg">
				 <div class="row"><div class="span9">Select an existing  course</div></div>
				  <%= university_course_form.input :course_id , collection: Course.all, label_method: :name , value_method: :id %>
			</div><div class="well bisqueBg">
				  <div class="row"><div class="span9">OR create a course</div></div>
				  <%= university_course_form.simple_fields_for :course do |course_form| %>
					  <% if action == "edit" then %>
					  <%= course_form.input :id, :as => :hidden, :input_html => { :value => course_form.object.id } %>
					  <% end %>
					    <%= course_form.input :name %>
					    <%= course_form.input :practical %>
					    <%= course_form.input :branch_id, collection: Branch.all, label_method: :name , value_method: :id %>
				  <% end %> <%# course_form ends %>
				</div><div class="well bisqueBg">
					  <div class="row"><div class="span9">Add Units</div></div>
					
						  <%= university_course_form.simple_fields_for :units do |unit_form| %>
							   <div class="well aliceBlueBg">
							  <% if action == "edit" then %>
							  <%= unit_form.input :id, :as => :hidden, :input_html => { :value => unit_form.object.id } %>
							  <% end %>
							    <%= unit_form.input :unit_number %>
						   <%= unit_form.input :name %>
							    Curriculum for Unit : 
							    <%= unit_form.text_area :unit_curriculum , class: "fullWidth" %>
							   </div>
						  <% end %> <%# unit_form ends %>
				</div><%# well ends %>
		 <% end %> <%# university_course_form ends %> 
		</div><%# well ends %>  
    </div> 
  <% end %> <%# program_university_course_form ends %>  

  <p><%= f.link_to_add( :program_university_courses, model_object: ProgramUniversityCourse.new.tap{ |puc| puc.university_course = UniversityCourse.new.tap { |uc| 5.times { uc.units.build };uc.course = Course.new } }, class: "btn btn-primary" ) do%>
   Add Course
   <% end %></p>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                programs_path, :class => 'btn' %>
  </div>
<% end %>

app/views/programs/_program_details.html.erb
  <div class="row" id="program_details">
    <div class="span12">
        
        <div class="row">
                <h4>Now choose a course:</h4></p>
        </div>
        <div class="row">
        <ul class="nav nav-tabs">
          <li class="active"><%= link_to "Semester 1", "#sem1courses", "data-toggle"=>"tab" %></li>
          <% (2..8).each do |n| %>
          <li><%= link_to "Semester #{n}", "#sem#{n}courses", "data-toggle"=>"tab" %></li>
          <% end %>
        </ul>
        </div>

        <div class="row">
          <div class="tab-content">
          <div class="tab-pane active" id="sem1courses">
            <ul class="thumbnails">
              <% p.program_university_courses.select{ |puc| puc.semester==1 && puc.university_course !=nil }.each do |puc1| %>
                <li class="span3">
                <div class="thumbnail coloredThumbnail">
                  <div align="center"><h5><%= link_to puc1.university_course.full_course_name, program_university_course_path(puc1.id)%></h5></div>
                </div>
                </li>
              <% end %>
            </ul>
          </div><!-- tab-pane active -->
          <% (2..8).each do |n| %>
          <%= content_tag :div , class: "tab-pane", id: "sem#{n}courses" do%>
            <ul class="thumbnails">
              <% p.program_university_courses.select{ |puc| puc.semester==n && puc.university_course !=nil }.each do |puc1| %>
                <li class="span3">
                <div class="thumbnail coloredThumbnail">
                  <div align="center"><h5><%= link_to puc1.university_course.full_course_name, program_university_course_path(puc1.id)%></h5></div>
                </div>
                </li>
              <% end %>
            </ul>
          <% end %>
          <% end %>
          </div><!-- tab-content -->
        </div><!-- row -->
    </div>
  </div> <!-- program_details -->

app/views/programs/edit.html.erb
<%- model_class = Program -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form', locals: {action: "edit" } %>

app/views/programs/index.html.erb
<%- model_class = Program -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:degree_name) %></th>
      <th>University</th>
      <th>Branch</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td><%= link_to program.id, program_path(program) %></td>
        <td><%= program.degree_name %></td>
        <td><%= program.university.name%></td>
        <td><%= program.branch.abbreviation %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_program_path(program), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      program_path(program),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_program_path,
            :class => 'btn btn-primary' %>

app/views/programs/new.html.erb
<%- model_class = Program -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form', locals: {action: "new" } %>

app/views/programs/schedule.html.erb
<div class="bordered-box">
  <div class="bordered-box-content">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <td><h5>Course Name</h5></td>
          <td><h5>Course Code</h5></td>
          <td><h5>Exam Date</h5></td>
          <td><h5>Session</h5></td>
        </tr>
      </thead>
      <tbody>
        <% cache(["v1",@program.university]) do %>
        <% @exams.each do |exam| %>
          <tr>
            <td><div class="customLink"><%= link_to exam.university_course.course.name, program_university_course_path(id: ProgramUniversityCourse.find_by(university_course_id: exam.university_course_id, program_id: @program.id )) %></div></td>
            <td><%= exam.university_course.course_code %></td>
            <td><%= exam.date.strftime("%d-%b-%y %A") %></td>
            <td><%= exam.session %></td>
          </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/programs/show.html.erb
<%- model_class = Program -%>
<% content_for :pagewise_heading do %>
	<%= @program.short_desc %>
<% end %>

<% content_for :navbar_breadcrumbs do %>
	<ul class="nav">
	  <li><%= link_to root_path do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
  <li><%= link_to branch_path(@program.branch_id) do %><%= @program.branch.name %> &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
</ul>
<% end %>


<% pucs= @program.program_university_courses.where.not(semester: nil).includes(university_course: :course).order("semester") %>
<% pucs_semwise = pucs.group_by { |puc| puc.semester } %>
<% elective_pucs = @program.program_university_courses.where(elective: true).includes(university_course: :course) %>

<div class="tabbable">
  <ul class="nav nav-tabs">
	  <li class="active"><%= link_to "Semester "+pucs_semwise.keys.first.to_s, "#sem"+pucs_semwise.keys.first.to_s , "data-toggle" => "tab" %></li>
	  <% pucs_semwise.keys[1..-1].each do |sem| %>
	  	<li><%= link_to "Semester "+sem.to_s, "#sem"+sem.to_s , "data-toggle" => "tab" %></li>
	  <% end %> 
	<li><%= link_to "Electives", "#electives" , "data-toggle" => "tab" %></li>   
  </ul>
  <div class="tab-content">
    <%= content_tag :div, class: "tab-pane active", id: "sem"+pucs_semwise.keys.first.to_s do %>
	<% pucs_semwise.values.first.each do |puc| %>
		<p><%= link_to puc.university_course.course_code+" - "+puc.university_course.course.name, university_course_path(puc.university_course_id) %></p>
	<% end %>
    <% end %>

    <% pucs_semwise.keys[1..-1].each_with_index do |sem, index| %>
      <%= content_tag :div, class: "tab-pane", id: "sem"+sem.to_s do %>
	<% pucs_semwise.values[index+1].each do |puc| %>
		<p><%= link_to puc.university_course.course_code+" - "+puc.university_course.course.name, university_course_path(puc.university_course_id) %></p>
	<% end %>
      <% end %>
    <% end %>
 
    <%= content_tag :div, class: "tab-pane", id: "electives" do %>
	<% elective_pucs.each do |puc| %>
		<p><%= link_to puc.university_course.course_code+" - "+puc.university_course.course.name, university_course_path(puc.university_course_id) %></p>
	<% end %>
    <% end %>
   
  </div>
</div>

<% if admin_signed_in? then %>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              programs_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_program_path(@program), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              program_path(@program),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<% end %>