config/routes.rb
Honeybadger::Application.routes.draw do
  get "feedbacks/new"
  get "feedbacks/create"
  get "search_results_controller/search"
  root 'pages#home'
  get "/home2" => "pages#home2"
 

  devise_scope :user do
	post "/users" => "users/registrations#append_or_create" , as: "user_registration"
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }

  devise_for :admins, controllers: { sessions: "admins/sessions" }

  get "home_programs_json" => 'programs#json_list'
  get "selectprogram" => "programs#select_program"

  
  get "pages/channel"
  get "/about" => "pages#about"
  get '/search/find_courses_from_program_and_semester' => 'search_results#find_courses_from_program_and_semester'
  get '/search/find_programs_from_university_and_branch' => 'search_results#find_programs_from_university_and_branch'
  get '/search/get_course' => 'search_results#get_course'
  get '/university_courses/:id/new_qpaper' => 'university_courses#new_qpaper' , as: "university_courses_new_qpaper"
  get '/courses/:id/new_question' => 'courses#new_question' , as: "course_new_question"
  
  post '/questions/:question_id/addanswer' => 'questions#submit_answer'
  post 'solutions/accept' => 'solutions#accept'
  get '/yourquestions' =>'questions#yourquestions'
  get '/youranswers' => 'solutions#yoursolutions'
  get '/schedule/:program/:semester' => 'programs#schedule'

  resources :qpapers
  resources :questions
  resources :courses
  resources :examquestions
  resources :branches
  resources :universities
  resources :programs
  resources :institutions
  resources :university_courses
  resources :solutions
  resources :wikis
  resources :notes
  resources :units
  resources :program_university_courses
  resources :qpaper_files
  resources :text_book_sale_offers, only: [:create, :update, :destroy]
  resources :feedbacks, only: [:new, :create]

  

end

app/models/qpaper_file.rb
class QpaperFile < ActiveRecord::Base
	has_attached_file :uploaded_file
	validates_attachment_presence :uploaded_file
end

app/controllers/qpaper_files_controller.rb
class QpaperFilesController < ApplicationController
  before_action :set_qpaper_file, only: [:show, :edit, :update, :destroy]

  # GET /qpaper_files
  # GET /qpaper_files.json
  def index
    @qpaper_files = QpaperFile.all
  end

  # GET /qpaper_files/1
  # GET /qpaper_files/1.json
  def show
  end

  # GET /qpaper_files/new
  def new
    @qpaper_file = QpaperFile.new
  end

  # GET /qpaper_files/1/edit
  def edit
  end

  # POST /qpaper_files
  # POST /qpaper_files.json
  def create
    puts params
    @qpaper_file = QpaperFile.new(qpaper_file_params)
    @qpaper_file.user_id = current_user.id
    respond_to do |format|
      if @qpaper_file.save
        format.html { redirect_to session[:previous_url], notice: 'Thanks for uploading the question paper. We will review it and add it to our database.' }
        format.json { render action: 'show', status: :created, location: @qpaper_file }
      else
        format.html { redirect_to session[:previous_url] ,notice: 'Sorry. There was some error in uploading the file. Please try again' }
        format.json { render json: @qpaper_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qpaper_files/1
  # PATCH/PUT /qpaper_files/1.json
  def update
    respond_to do |format|
      if @qpaper_file.update(qpaper_file_params)
        format.html { redirect_to @qpaper_file, notice: 'Qpaper file was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @qpaper_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qpaper_files/1
  # DELETE /qpaper_files/1.json
  def destroy
    @qpaper_file.destroy
    respond_to do |format|
      format.html { redirect_to qpaper_files_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qpaper_file
      @qpaper_file = QpaperFile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qpaper_file_params
      params.require(:qpaper_file).permit(:user_id, :university_course_id, :uploaded_file)
    end
end

app/helpers/qpaper_files_helper.rb
module QpaperFilesHelper
end

app/views/qpaper_files/_form.html.erb
<%= simple_form_for(@qpaper_file) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/qpaper_files/edit.html.erb
<h1>Editing qpaper_file</h1>

<%= render 'form' %>

<%= link_to 'Show', @qpaper_file %> |
<%= link_to 'Back', qpaper_files_path %>

app/views/qpaper_files/index.html.erb
<h1>Listing qpaper_files</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @qpaper_files.each do |qpaper_file| %>
      <tr>
        <td><%= link_to 'Show', qpaper_file %></td>
        <td><%= link_to 'Edit', edit_qpaper_file_path(qpaper_file) %></td>
        <td><%= link_to 'Destroy', qpaper_file, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Qpaper file', new_qpaper_file_path %>

app/views/qpaper_files/new.html.erb
<h1>New qpaper_file</h1>

<%= render 'form' %>

<%= link_to 'Back', qpaper_files_path %>

app/views/qpaper_files/show.html.erb
<p id="notice"><%= notice %></p>


Click <%= link_to "here", @qpaper_file.uploaded_file.url %> to download the question paper.