config/routes.rb
Honeybadger::Application.routes.draw do
  get "feedbacks/new"
  get "feedbacks/create"
  get "search_results_controller/search"
  root 'pages#home'
  get "/home2" => "pages#home2"
 

  devise_scope :user do
	post "/users" => "users/registrations#append_or_create" , as: "user_registration"
  end
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", sessions: "users/sessions" }

  devise_for :admins, controllers: { sessions: "admins/sessions" }

  get "home_programs_json" => 'programs#json_list'
  get "selectprogram" => "programs#select_program"

  
  get "pages/channel"
  get "/about" => "pages#about"
  get '/search/find_courses_from_program_and_semester' => 'search_results#find_courses_from_program_and_semester'
  get '/search/find_programs_from_university_and_branch' => 'search_results#find_programs_from_university_and_branch'
  get '/search/get_course' => 'search_results#get_course'
  get '/university_courses/:id/new_qpaper' => 'university_courses#new_qpaper' , as: "university_courses_new_qpaper"
  get '/courses/:id/new_question' => 'courses#new_question' , as: "course_new_question"
  
  post '/questions/:question_id/addanswer' => 'questions#submit_answer'
  post 'solutions/accept' => 'solutions#accept'
  get '/yourquestions' =>'questions#yourquestions'
  get '/youranswers' => 'solutions#yoursolutions'
  get '/schedule/:program/:semester' => 'programs#schedule'

  resources :qpapers
  resources :questions
  resources :courses
  resources :examquestions
  resources :branches
  resources :universities
  resources :programs
  resources :institutions
  resources :university_courses
  resources :solutions
  resources :wikis
  resources :notes
  resources :units
  resources :program_university_courses
  resources :qpaper_files
  resources :text_book_sale_offers, only: [:create, :update, :destroy]
  resources :feedbacks, only: [:new, :create]

  

end

app/models/qpaper.rb
class Qpaper < ActiveRecord::Base
        has_many :examquestions , dependent: :destroy
	has_many :questions, through: :examquestions
	belongs_to :university_course, touch: true
	belongs_to :user
	has_and_belongs_to_many :programs

	accepts_nested_attributes_for :examquestions,  reject_if: proc { |attributes| attributes['qnumber'].blank? || attributes['mark'].blank? }

	def full_title
		return self.title+" "+self.month+" "+self.year.to_s
	end
end

app/controllers/qpapers_controller.rb
class QpapersController < ApplicationController
  before_action :set_qpaper, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :find]

  # GET /qpapers
  # GET /qpapers.json
  def index
    @qpapers = Qpaper.all
  end

  # GET /qpapers/1
  # GET /qpapers/1.json
  def show
	  if params[:puc] then
		  @puc=ProgramUniversityCourse.find(params[:puc])
	  else
		  @puc=nil
	  end
    
  end

  # GET /qpapers/new
  def new
    @qpaper = Qpaper.new
    @qpaper.examquestions.build.build_question
    #@examquestion=@qpaper.examquestions.build
    #@examquestion.build_question
  end

  # GET /qpapers/1/edit
  def edit
  end

  # POST /qpapers
  # POST /qpapers.json
  def create
    @qpaper = Qpaper.new(qpaper_params)  
    @qpaper.user_id = current_user.id
    @qpaper.examquestions.each do |eq|
	 eq.user_id = current_user.id
	 eq.question.user_id ||= current_user.id
	 eq.question.course_id ||= UniversityCourse.find(@qpaper.university_course_id).course_id
    end
    respond_to do |format|
      if @qpaper.save!
        format.html { redirect_to @qpaper, notice: 'Qpaper was successfully created.' }
        format.json { render action: 'show', status: :created, location: @qpaper }
      else
        format.html { render action: 'new' }
        format.json { render json: @qpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /qpapers/1
  # PATCH/PUT /qpapers/1.json
  def update
    respond_to do |format|
      puts qpaper_params
      if @qpaper.update(qpaper_params)
        format.html { redirect_to @qpaper, notice: 'Qpaper was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @qpaper.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /qpapers/1
  # DELETE /qpapers/1.json
  def destroy
    @qpaper.destroy
    respond_to do |format|
      format.html { redirect_to qpapers_url }
      format.json { head :no_content }
    end
  end
 
  # GET /qpapers/find
  def find
    @qpapers=UniversityCourse.find(qpaper_search_params[:university_course]).qpapers
    render action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_qpaper
      @qpaper = Qpaper.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def qpaper_params
      params.require(:qpaper).permit(:year, :title, :exam_name,  :official, :university_course_id, :program_ids, :month, :semester,  examquestions_attributes: [:mark, :qnumber, :id, :question_id,:subquestion_no,  {question_attributes: [:qtext, :qdesc, :id]}])
    end

    def qpaper_search_params
    	params.permit(:program, :university, :university_course, :commit, :controller, :action)
    end

    def authenticate_user_or_admin!
	if admin_signed_in?
		authenticate_admin!
	else
		authenticate_user!
	end
    end
end

app/helpers/qpapers_helper.rb
module QpapersHelper
	def user_has_access?
	end
end

app/views/qpapers/_editform.html.erb
<%= simple_nested_form_for @qpaper, :html => { :class => 'form-horizontal' } do |f| %>
	<div class="well">
  <%= f.input :year , collection: 2013.downto(1990) %>
  <%= f.input :title %>
  <%= f.input :exam_name %>
  <%= f.association :university_course , label_method: :full_course_name %>
  <%= f.association :programs , label_method: :short_desc, as: :check_boxes %>
  <%= f.input :month %>
  <%= f.input :semester %>
  <%= f.input :official %>
	</div>
	<%= f.simple_fields_for :examquestions, @qpaper.examquestions  do |eq| %>
		<div class="well">
			<%= eq.input :qnumber, label: "Question Number:"  %>
			<%= eq.input :mark, label: "Mark:"  %>
			<%= eq.input :subquestion_no, label: "Sub-question number:"  %>
			<%= eq.input :id, :as => :hidden, :input_html => { :value => eq.object.id } %>
			<% if eq.object.question.user_id == current_user.id %>
			   <%= eq.simple_fields_for :question do |q| %>
				    <%= q.input :id, :as => :hidden, :input_html => { :value => q.object.id } %>
				    <%= q.input :qtext, label: "Question:"  %>
				    <%= q.input :qdesc, label: "Question Details:"  %>
			   <% end %> 
			<% else %>
				<%= eq.association :question , label_method: :qtext %>
			<% end %>
    		</div> 
	<% end %> 
	<p><%= f.link_to_add( :examquestions, model_object: lambda {e= @qpaper.examquestions.build; e.question= Question.new; return e;}, class: "btn btn-primary" ) do%>
		Add Question
	<% end %></p>
	<div class="form-actions">
		<%= f.button :submit, :class => 'btn-primary' %>
		<%= link_to t('.cancel', :default => t("helpers.links.cancel")), qpapers_path, :class => 'btn' %>
	</div>
<% end %>

app/views/qpapers/_form.html.erb
<%= simple_nested_form_for @qpaper, :html => { :class => 'form-horizontal' } do |f| %>
<div class="well">
  <%= f.input :year , collection: 2013.downto(1990) %>
  <%= f.input :title %>
  <%= f.input :exam_name %>
  <%= f.association :university_course , label_method: :full_course_name %>
  <%= f.association :programs , label_method: :short_desc, as: :check_boxes %>
  <%= f.input :month %>
  <%= f.input :semester %>
  <%= f.input :official %>
</div>
  <%= f.simple_fields_for :examquestions do |examquestion_form| %>
    <div class="well">
	    <%= examquestion_form.input :qnumber, label: "Question Number:"  %>
	    <%= examquestion_form.input :mark, label: "Mark:"  %>
	    <%= examquestion_form.input :subquestion_no, label: "Sub-question number:"  %>
		   <%= examquestion_form.association :question ,label_method: :qtext %>
			<div class="row"><div class="span1 offset3">OR</div></div>
		   <%= examquestion_form.simple_fields_for :question do |question_form| %>
		    <%= question_form.input :qtext, label: "Question:"  %>
		    <%= question_form.input :qdesc, label: "Question Details:"  %>
		  <% end %>   
    </div> 
  <% end %>
  <p><%= f.link_to_add( :examquestions, model_object: Examquestion.new.tap{ |eq| eq.build_question }, class: "btn btn-primary" ) do%>
   Add Question
   <% end %></p>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                qpapers_path, :class => 'btn' %>
  </div>
<% end %>

app/views/qpapers/edit.html.erb
<%- model_class = Qpaper -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'editform' %>

app/views/qpapers/index.html.erb
<%- model_class = Qpaper -%>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Id</th>
      <th> Title </title>
      <th>Year</th>
      <th>Course</th>
      <% if admin_signed_in? then %>
      	<th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @qpapers.each_with_index do |qpaper, index| %>
      <tr>
        <td><%= index+1 %></td>
	<td><%= link_to qpaper.title + " - " + qpaper.month, qpaper_path(qpaper.id) %></td>
        <td><%= qpaper.year %></td>
        <td><%= qpaper.university_course.try(:full_course_name) %></td>
	<% if admin_signed_in? then %>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_qpaper_path(qpaper), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      qpaper_path(qpaper),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_qpaper_path,
            :class => 'btn btn-primary' %>

app/views/qpapers/no_results.html.erb
<h2>No results matched your query</h2>

app/views/qpapers/show.html.erb
<% content_for :mathjax_scripts do %>
<%= render partial: 'partials/mathjax_include' %>
<% end %>
<% content_for :prettify_scripts do %>
<%= render partial: 'partials/prettify_include' %>
<% end %>
<% content_for :title do %>
<%= "Karpeer - "+@qpaper.university_course.full_course_name+" - "+@qpaper.full_title %>
<% end %>

<% content_for :pagewise_heading do %>
<%= @qpaper.full_title %>&nbsp;&nbsp;<%= @qpaper.university_course.try(:full_course_name) %>
<% end %>


<% content_for :navbar_breadcrumbs do %>
<ul class="nav">
<% if @puc %>
  <li><%= link_to root_path do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
  <li><%= link_to program_university_course_path(@puc.id) do %><%= @puc.full_course_name %> &nbsp;&nbsp;<i class="icon-double-angle-right"></i> <% end %></li>
  <li><%= link_to @qpaper.full_title, '#' %></li>
<% elsif @uc%>
  <li><%= link_to root_path do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
  <li><%= link_to university_course_path(@uc.id) do %><%= @uc.full_course_name %> &nbsp;&nbsp;<i class="icon-double-angle-right"></i> <% end %></li>
  <li><%= link_to @qpaper.full_title, '#' %></li>
<% else %>
  <li><%= link_to root_path  do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><%end %></li>
  <li><%= link_to @qpaper.full_title, '#' %></li>
<% end %>
	</ul>
<% end %>


<div class="right-bordered-box">
<div class="bordered-box-content">
<table class="table table-condensed">

<thead>
<tr>
<th>Q.No.</th><th>Question</th><th>Marks</th>
</tr>
</thead>

<tbody>
<% cache [ "v5" , qpaper_questions(@qpaper) ] do%>
<% @qpaper.examquestions.order("qnumber ASC, subquestion_no ASC").includes(:question).each do |eq| %>
	<% cache [ "v5", eq.question ] do %>
		<% if !eq.subquestion_no.nil? && eq.subquestion_no > 1 && ( eq.subsubqno == 1 || eq.subsubqno.nil? ) then %>
		<tr><td></td><td>OR</td><td></td></tr>
		<% end %>
		  <tr>
			<td><%= eq.qnumber.to_s %><%= eq.subquestion_no.nil? ? "" : "."+('a'.ord+eq.subquestion_no-1).chr %><%= eq.subsubqno.nil? ? "" : "."+roman_numeral(eq.subsubqno) %></td>
			  <td><div class="customLink">
        <% if @puc %>
          <%=link_to raw(render_markdown(eq.question.qtext)), question_path(eq.question_id)+"?puc="+@puc.id.to_s+"&qpaper="+@qpaper.id.to_s %>
        <% elsif @uc %>
          <%=link_to raw(render_markdown(eq.question.qtext)), question_path(eq.question_id)+"?uc="+@uc.id.to_s+"&qpaper="+@qpaper.id.to_s %>
        <% else %>
          <%=link_to raw(render_markdown(eq.question.qtext)), question_path(eq.question_id)+"?qpaper="+@qpaper.id.to_s %>
        <% end %>
        </div></td>
			  <td><%= eq.mark.to_s %></td>
			 <%# pucid = "nil" %>
			 <%# pucid = @puc.id.to_s unless @puc.nil? %>
		  </tr>
	 <% end %>
<% end %>
<% end %>
</tbody>

</table>
</div>
</div>

app/views/qpapers/show2.html.erb
<% content_for :mathjax_scripts do %>
<%= render partial: 'partials/mathjax_include' %>
<% end %>
<% content_for :prettify_scripts do %>
<%= render partial: 'partials/prettify_include' %>
<% end %>
<% content_for :title do %>
<%= "Karpeer - "+@qpaper.university_course.full_course_name+" - "+@qpaper.full_title %>
<% end %>

<% content_for :pagewise_heading do %>
<%= @qpaper.full_title %>&nbsp;&nbsp;<%= @qpaper.university_course.try(:full_course_name) %>
<% end %>


<% content_for :navbar_breadcrumbs do %>
<ul class="nav">
<% if @puc %>
  <li><%= link_to root_path do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
  <li><%= link_to program_university_course_path(@puc.id) do %><%= @puc.full_course_name %> &nbsp;&nbsp;<i class="icon-double-angle-right"></i> <% end %></li>
  <li><%= link_to @qpaper.full_title, '#' %></li>
<% elsif @uc%>
  <li><%= link_to root_path do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><% end %></li>
  <li><%= link_to university_course_path(@uc.id) do %><%= @uc.full_course_name %> &nbsp;&nbsp;<i class="icon-double-angle-right"></i> <% end %></li>
  <li><%= link_to @qpaper.full_title, '#' %></li>
<% else %>
  <li><%= link_to root_path  do %>Home &nbsp;&nbsp;<i class="icon-double-angle-right"></i><%end %></li>
  <li><%= link_to @qpaper.full_title, '#' %></li>
<% end %>
	</ul>
<% end %>


<div class="right-bordered-box">
<div class="bordered-box-content">
<table class="table table-condensed">

<thead>
<tr>
<th>Q.No.</th><th>Question</th><th>Marks</th>
</tr>
</thead>

<tbody>
<% cache [ "v5" , qpaper_questions(@qpaper) ] do%>
<% @qpaper.examquestions.order("qnumber ASC, subquestion_no ASC").includes(:question).each do |eq| %>
	<% cache [ "v5", eq.question ] do %>
		<% if !eq.subquestion_no.nil? && eq.subquestion_no > 1 && ( eq.subsubqno == 1 || eq.subsubqno.nil? ) then %>
		<tr><td></td><td>OR</td><td></td></tr>
		<% end %>
		  <tr>
			<td><%= eq.qnumber.to_s %><%= eq.subquestion_no.nil? ? "" : "."+('a'.ord+eq.subquestion_no-1).chr %><%= eq.subsubqno.nil? ? "" : "."+roman_numeral(eq.subsubqno) %></td>
			  <td><div class="customLink">
        <% if @puc %>
          <%=link_to raw(render_markdown(eq.question.qtext)), question_path(eq.question_id)+"?puc="+@puc.id.to_s+"&qpaper="+@qpaper.id.to_s %>
        <% elsif @uc %>
          <%=link_to raw(render_markdown(eq.question.qtext)), question_path(eq.question_id)+"?uc="+@uc.id.to_s+"&qpaper="+@qpaper.id.to_s %>
        <% else %>
          <%=link_to raw(render_markdown(eq.question.qtext)), question_path(eq.question_id)+"?qpaper="+@qpaper.id.to_s %>
        <% end %>
        </div></td>
			  <td><%= eq.mark.to_s %></td>
			 <%# pucid = "nil" %>
			 <%# pucid = @puc.id.to_s unless @puc.nil? %>
		  </tr>
	 <% end %>
<% end %>
<% end %>
</tbody>

</table>
</div>
</div>